site_name: Mini Projects
nav:
  - Home: index.md
  - React:
      - Start Here: react/resources.md
      - Multiplication Tables: react/1-multiplication-tables.md
      - Color Picker: react/2-color-picker.md
  - Svelte:
      - Start Here: svelte/resources.md
      - Multiplication Tables: svelte/1-multiplication-tables.md
      - Color Picker: svelte/2-color-picker.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages: ['lua', 'javascript', 'python']
extra_css:
  - css/style.css
