site_name: Mini Projects
nav:
  - Home: index.md
  - React:
      - Start Here: react/resources.md
      - Multiplication Tables: react/1-multiplication-tables.md
      - Color Picker: react/2-color-picker.md
      - Move Div: react/3-move-div.md
  - Svelte:
      - Start Here: svelte/resources.md
      - Multiplication Tables: svelte/1-multiplication-tables.md
      - Color Picker: svelte/2-color-picker.md
  - SwiftUI:
      - Start Here: swiftui/resources.md
      - Multiplication Tables: swiftui/1-multiplication-tables.md
      - Color Picker: swiftui/2-color-picker.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages: ['lua', 'javascript', 'python', 'swift']
extra_css:
  - css/style.css
